import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LandingBanner from '../components/Present/Landing/LandingBanner'
import LandingBody from '../components/Present/Landing/LandingBody'
import CurlentFull from '../public/logo/CurlentFull.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Curlent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='grid grid-cols-1'>
        <LandingBanner />
        <LandingBody />

      </main>

      <footer className="flex justify-center items-center py-10 w-full border-t-2" >
        <Image
          className='w-6/12'
          src={CurlentFull}
          height={100} width={500}
          objectFit="contain"
        />

        <p className='text-xl w-6/12'>
          © 2022 Curlent ,Inc.
        </p>

      </footer>
    </div>
  )
}
