import Head from 'next/head'
import Image from 'next/image'
import LandingBanner from '../components/Present/Landing/LandingBanner'
import LandingBody from '../components/Present/Landing/LandingBody'
import CurlentFull from '../public/logo/CurlentFull.png'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Curlent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='grid grid-cols-1'>
        <LandingBanner />
        <LandingBody />

        <button 
          className='text-2xl border-2 bg-amber-300 font-medium w-fit p-5 place-self-center rounded mb-32'
          onClick={() => router.push("/payment/checkout/preview")}
        >
            Try Curlent Payment now
        </button>


      </main>

      <footer className="flex justify-center items-center py-10 w-full border-t-2" >
        <Image
          className='w-6/12'
          src={CurlentFull}
          height={100} width={500}
          objectFit="contain"
        />

        <p className='text-xl w-6/12'>
          © 2022 Curlent ,Inc.
        </p>

      </footer>
    </div>
  )
}
